meduzer/blog/urls.py
from django.conf.urls import url
from django.urls import path, include

from .views import *

app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="posts_list_url"),
    path("post/create/", PostCreate.as_view(), name="post_create_url"),
    path("post/<slug:slug>/", PostDetail.as_view(), name="post_detail_url"),
    path("post/<str:slug>/update/", PostUpdate.as_view(), name="post_update_url"),
    path("post/<str:slug>/delete/", PostDelete.as_view(), name="post_delete_url"),
    # path("<int:post_id>/share/", views.post_share, name="post_share"),
    # path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("search/", SearchResultsView.as_view(), name="search_results"),
    path("tags/", TagsView.as_view(), name="tags_list_url"),
    path("tags/create/", TagCreate.as_view(), name="tag_create_url"),
    path("tags/<str:slug>/", TagDetail.as_view(), name="tag_detail_url"),
    path("tags/<str:slug>/update/", TagUpdate.as_view(), name="tag_update_url"),
    path("tags/<str:slug>/delete/", TagDelete.as_view(), name="tag_delete_url"),
    url(r"^comments/", include("django_comments.urls")),
]

meduzer/meduzer/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# from blog.sitemaps import PostSitemap
# from meduzer.meduzer.views import redirect_blog

# sitemaps = {
#     "posts": PostSitemap,
# }

urlpatterns = [
    # path('', redirect_blog),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("blog.urls")),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemaps},
    #     name="django.contrib.sitemaps.views.sitemap",
    # ),
    path("social-auth/", include("social_django.urls", namespace="social")),
    url("avatar/", include("avatar.urls")),
    url(r"^comments/", include("django_comments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meduzer/blog/models.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.postgres.indexes import GinIndex
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class Post(models.Model):
    DoesNotExist = None
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        verbose_name="Авторство",
        related_name="blog_posts",
        related_query_name="post",
    )
    title = models.CharField(
        max_length=255,
        blank=False,
        unique=True,
        db_index=True,
        help_text=True,
        null=False,
    )
    slug = models.SlugField(
        max_length=150,
        unique=True,
        blank=True,
        null=True,
        db_index=True,
        allow_unicode=True,
        unique_for_date="publish",
    )
    post_subject = models.CharField(
        max_length=255, blank=False, null=False, db_index=True, default=""
    )
    annotation = models.TextField(max_length=600, blank=True, null=True, db_index=True)
    post_keywords = models.CharField(
        max_length=100, blank=True, null=True, db_index=True
    )
    body = models.TextField(
        blank=True, null=True, db_index=True, verbose_name="Основная часть"
    )
    findings = models.CharField(max_length=600, blank=True, null=True, db_index=True)
    bibliography = models.CharField(
        max_length=600, blank=True, null=True, db_index=True
    )
    # tags = models.ManyToManyField(
    #     "Tag", blank=True, null=True, related_name="posts", verbose_name="Присвойте метки:"
    # )
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail_url", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("blog:post_update_url", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("blog:post_delete_url", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        super(Post, self).save()
        if not self.slug:
            slug = slugify(self.title)
            try:
                post_obj = Post.objects.get(slug=slug)
                slug += "-" + str(self.id)
            except Post.DoesNotExist:
                pass
            self.slug = slug
            self.save()

    class Meta:
        ordering = ("-publish",)
        indexes = [
            GinIndex(fields=["title"], name="gin_trgm_idx", opclasses=["gin_trgm_ops"])
        ]
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"

    def __str__(self):
        return f"{self.title}"


# class Comment(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name='Комментарии')
#     # name = models.CharField(max_length=80)
# email = models.EmailField()
#     author = models.ForeignKey(User, related_name="comment_author", on_delete=models.CASCADE, verbose_name="Автор")
#     body = models.TextField(verbose_name='Комментарий')
#     created = models.DateTimeField("Опубликовано", auto_now_add=True)
#     updated = models.DateTimeField("Обновлено", auto_now=True)
#     active = models.BooleanField(default=True)
#
#     class Meta:
#         ordering = ("created",)
#         verbose_name='Комментарий'
#         verbose_name_plural="Комментарии"
#
#     def __str__(self):
#         return f"Комментарий от {self.author} к публикации {self.post}"


class Tag(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название метки")
    slug = models.SlugField(
        max_length=100, unique=True, verbose_name="In english, please"
    )

    # Функция используется для получения ссылки (каноническая ссылка - соглашение Джанго) на объект
    def get_absolute_url(self):
        return reverse("blog:tag_detail_url", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("blog:tag_update_url", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("blog:tag_delete_url", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ["title"]

meduzer/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from pagedown.widgets import PagedownWidget

from .models import Post, Tag


# class EmailPostForm(forms.Form):
#     name = forms.CharField(max_length=25)
#     email = forms.EmailField()
#     to = forms.EmailField()
#     comments = forms.CharField(required=False, widget=forms.Textarea)

#
# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ("body",)
#
#     def save(self, commit=True):
#         comment = super(CommentForm, self).save(commit=False)
#         comment.content = self.cleaned_data['body']
#
#         if commit:
#             comment.save()
#         return comment


class SearchForm(forms.Form):
    query = forms.CharField(max_length=150)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["title", "slug"]

        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "slug": forms.TextInput(attrs={"class": "form-control"}),
        }

    def clean_slug(self):
        # import pudb;pu.db
        new_slug = self.cleaned_data["slug"].lower()

        if new_slug == "create":
            raise ValidationError("Slug не может быть создан")
        if Tag.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError(
                f"Slug должен быть уникальным. {new_slug} уже существует."
            )
        return new_slug


class PostForm(forms.ModelForm):

    body = forms.CharField(
        widget=PagedownWidget(),
        label="Содержание публикации",
        help_text="Воспользуйтесь панелью редактирования для работы с текстом",
    )
    bibliography = forms.CharField(
        widget=PagedownWidget(), label="Поделитесь полезными источниками"
    )
    findings = forms.CharField(
        widget=PagedownWidget(),
        label="В заключении подведите итог и сформулируйте выводы",
    )

    class Meta:
        model = Post
        fields = "__all__"
        exclude = ["publish", "updated", "author", "slug"]
        # разобраться с автозаполнением даты публикации (необязательно, но попробовать)
        widgets = {
            # "author": forms.TextInput(attrs={"author": "user.first_name"}) ,
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "post_subject": forms.TextInput(attrs={"class": "form-control"}),
            "annotation": forms.TextInput(attrs={"class": "form-control"}),
            "post_keywords": forms.TextInput(attrs={"class": "form-control"}),
            "findings": forms.TextInput(attrs={"class": "form-control"}),
            "slug": forms.TextInput(attrs={"class": "form-control"}),
            "tags": forms.SelectMultiple(attrs={"class": "form-control"}),
            # 'publish': forms.DateTimeField(widget=DateTimeInput())
        }

        labels = {
            "title": _("Заголовок публикации"),
            "slug": _("Слаг публикации"),
            "post_subject": _("Предмет публикации (необязательное поле)"),
            "annotation": _("Аннотация (необязательное поле)"),
            "post_keywords": _("Ключевые слова (необязательное поле)"),
            "body": _("Основная часть"),
            "findings": _("Выводы (необязательное поле)"),
            "bibliography": _("Источники и полезные ресурсы (необязательное поле)"),
        }

        help_texts = {
            "title": _("Используйте простые конструкции для оформления заголовка"),
            "post_subject": _("Кратко опишите предмет изучения, либо исследования"),
            "annotation": _(
                "Составьте краткий анонс Вашей публикации: назначение, методы работы, особое внимание к "
                "деталям и отличительные особенности"
            ),
            "post_keywords": _(
                "Используйте ключевые для обнаружения вашей публикации поисковыми сервисами"
            ),
            "findings": _(
                "Подведите итоги Вашей работы для лучшего восприятия читателями ресурса"
            ),
            "tags": _("Присвоение тегов облегчит поиск информации на Medbrain"),
        }

        error_messages = {
            "Post._meta.get_fields()": {
                "max_length": _("Количество символов превышает допустимое"),
            }
        }

meduzer/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.postgres.search import SearchVector
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    CreateView,
    FormView,
    DeleteView,
)
from django.views.generic.base import View

from .forms import PostForm, TagForm, SearchForm
from .models import Post, Tag
from .postforms.postforms import FullPostForm
from .utils import (
    ObjectCreateMixin,
    ObjectUpdateMixin,
    ObjectDeleteMixin,
    timezone,
)


class PostCreate(LoginRequiredMixin, CreateView, FormView):
    model = Post
    form_class = FullPostForm
    template_name = "blog/post/post_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        from django.http import HttpResponseRedirect

        return HttpResponseRedirect(self.get_success_url())


class PostDetail(DetailView):
    model = Post
    template_name = "blog/post/post_detail.html"
    redirect_url = reverse_lazy("blog:post_detail_url")

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context["now"] = timezone.now()
        return context


class PostListView(ListView):
    model = Post
    paginate_by = 10
    template_name = "blog/post/post_list.html"


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post/post_update_form.html"

    def test_func(self):
        return self.get_object().author == self.request.user


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "blog/post/post_delete_form.html"
    success_url = reverse_lazy("blog:posts_list_url")

    def test_func(self):
        return self.get_object().author == self.request.user


class TagDetail(DetailView):
    model = Tag
    template_name = "blog/tags/tag_detail.html"


class TagCreate(LoginRequiredMixin, ObjectCreateMixin, View):
    model_form = TagForm
    template = "blog/tags/tag_create.html"
    raise_exception = True


class TagUpdate(LoginRequiredMixin, UserPassesTestMixin, ObjectUpdateMixin, View):
    model = Tag
    model_form = TagForm
    template = "blog/tags/tag_update_form.html"
    raise_exception = True


class TagDelete(LoginRequiredMixin, UserPassesTestMixin, ObjectDeleteMixin, View):
    model = Tag
    template = "blog/tags/tag_delete_form.html"
    redirect_url = reverse_lazy("tags_list_url")
    raise_exception = True


class TagsView(ListView):
    model = Tag
    template_name = "blog/tags/tags_list.html"


class SearchResultsView(ListView):
    model = Post
    template_name = "blog/post/search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Post.objects.filter(
            Q(title__icontains=query)
            | Q(body__icontains=query)
            | Q(post_keywords__icontains=query)
        )
        return object_list

meduzer/blog/templates/blog/post/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }} - {{ block.super }}
{% endblock %}

{% block content %}
    <h1 class="mt-5">
        {{ post.title }}
    </h1>
    <p>
        {{ post.body }}
    </p>
{% endblock %}

meduzer/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}"> {{post.title}} </a> </li>
    {% endfor %}
</ul>

meduzer/blog/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>Блог того то того то</h1>

  {% if tag %}
    <h2> Статьи по тегам "{{ tag.name }}" </h2>
  {% endif %}

  {% for post in posts %}
    <h5>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h5>

    <p class="tags">
      Тэги:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>

    <p class="date">
      Опубликовано {{ post.publish }} : {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

meduzer/blog/templates/blog/post/post_create_form.html
{% extends 'base.html' %}


{% block title %}
    Создать публикацию - {{block.super}}
{% endblock %}

    {% block mark_style %}
    {{ form.media }}
    {% endblock mark_style %}

{% block content %}

    <form  class="" action="{% url 'blog:post_create_url' %}" method="post">

        {% csrf_token %}
        <style class="text/css">
            .wmd-button-row {
            background: white;
            margin:-top: 1rem;
            margin-bottom: 1rem;
            margin-left:0;
            margin-right:0;
            }
            .wmd-panel {
            width: initial;
            margin: 0;
            }
            .wmd-input {
            background: white;
            }
            .form-group {
            margin-top:20px;
            }
            .form-control {
            margin-top:10px;
            margin-bottom:20px;
            }
        </style>
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" name="button" class="btn btn-primary btn-sm" style="margin-bottom: 20px;"> Опубликовать</button>
        <a href="{% url 'blog:tag_create_url' %}" type="submit" name="button" class="btn btn-warning btn-sm float-right" style="margin-bottom: 20px;"> Создать метку</a>
    </form>
{% endblock %}

meduzer/blog/templates/blog/post/post_delete_form.html
{% extends 'base.html' %}

{% block title %}
    Удалить публикацию: "{{ post.title|title }}" - {{ block.super }}
 {% endblock %}


 {% block content %}
    <form action="{{ post.get_delete_url }}" method="post">
        {% csrf_token %}
        <h4>Вы действительно хотите удалить публикацию: <b>"{{ post.title|title }}"?</b></h4>
        <a href="{{ post.get_absolute_url }}">Отменить</a>
        <button type="submit" name="button" class="btn btn-danger btn-sm">Удалить</button>
    </form>
 {% endblock %}

meduzer/blog/templates/blog/post/post_detail.html
{% extends 'base.html' %}
{% load avatar_tags %}
{% load blog_tags %}
{% load comments %}
{% block title %}
    {{ post.title }} - {{ block.super }}
{% endblock %}


{% block content %}
    <div class="card">
            <img src="https://img3.goodfon.ru/original/1920x1080/9/df/nastroeniya-kniga-knizhka.jpg" class="card-img-top" style="height:300px">
        <h3 class="card-header">{{ post.title }}</h3>

        <div class="card-body">
<!--        <h5 class="card-title">Специальный заголовок</h5>-->

            <p class="card-text">{{ post.post_subject|markdown }}</p>
            <p class="annotation">{{ post.annotation|markdown }}</p>
            <p class="card-text">{{ post.post_keywords|markdown }}</p>
            <p class="card-text">{{ post.body|markdown }}</p>
            <p class="card-text">{{ post.findings|markdown }}</p>
            <p class="card-text">{{ post.bibliography|markdown }}</p>
<!--        <a href="#" class="btn btn-primary">Переход куда-нибудь</a>-->
         </div>
        <div class="card-footer text-muted">
            <p class="text-muted" style="font-size:14px; margin-bottom:0px"><i class="fas fa-id-card-alt"></i> Автор: {{ post.author.first_name }} {{ post.author.last_name }}</p>
            <p class="text-muted" style="font-size:14px; margin-bottom:0px"><i class="far fa-calendar-alt"></i> Опубликовано: {{ post.publish}}</p>
            <p class="text-muted" style="font-size:14px; margin-bottom:0px"><i class="fas fa-tags"></i>
            Связанные метки:
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
            {% endfor %}
            </p>
            <p class="text-muted" style="font-size:14px; margin-bottom:0px"><i class="far fa-comments"></i> {% get_comment_count for post as comment_count %}Всего комментариев: {{ comment_count }}</p>
<!--            Эта хрень работает не так как надо. Потому что кривые урлы в кнопках не хотят работать-->
<!--            Редактирование и удаление публикации надо привязать к почте-->
            {% if user.is_authenticated %}
                {% if post.author.last_name == user.last_name %}
                    <a href="{% url 'blog:post_delete_url' post.slug %}" type="submit" name="button" class="btn btn-outline-danger btn-sm float-right" style="margin-left:10px"> Удалить</a>
                    <a href="{% url 'blog:post_update_url' post.slug %}" type="submit" name="button" class="btn btn-outline-info btn-sm float-right" style=""> Редактировать</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="card" style="margin-top: 20px;">
        <h6 class="card-header"> Обсуждение публикации автора: {{ post.author.first_name }} {{ post.author.last_name }}. </h6>
        <div class="card-body">
            {% if user.is_authenticated %}
                {% get_comment_form for post as form %}
                <form action="{% comment_form_target %}" method="post">
                {% csrf_token %}
                {{ form.comment }}
                {{ form.honeypot }}
                {{ form.content_type }}
                {{ form.object_pk }}
                {{ form.timestamp }}
                {{ form.security_hash }}
        <!--            не работает редирект на страницу публикации. ругается на миксин ObjectDetailView -->
                <style class="text/css">
                    #id_honeypot {
                        display: none;
                    }
                    #id_comment {
                    width: 100%;
                    min-height: 100px;
                    }

                </style>
                <button type="submit" name="button" class="btn btn-primary" id="id_submit" style="margin-top: 20px;"> Опубликовать</button>
                </form>
            {% else %}
                <p>Только зарегистрированные пользователи принимают участие в обсуждении!
                Пожалуйста, <a href="{% url 'login' %}">войдите в учетную запись</a>, чтобы оставить комментарий.</p>
            {% endif %}

        </div>
    </div>
    <div class="card" style="margin-top: 20px;">
        <h6 class="card-header">
            Комментарии
        </h6>
        <div class="card-body">
            {% get_comment_list for post as comment_list %}
            {% for comment in comment_list %}
            <style class="text/css">
                .id_user_avatar {
                margin-top: 20px;
                margin-bottom: 40px;
                }
            </style>
                {% avatar user 35 class="img-circle img-responsive" id="user_avatar" %} {{ comment.user_name }}, {{ comment.submit_date }}
                <p style="padding: 30px; margin: 20px; border-top-width: 1px; border-bottom-width: 1px; border-top-style: solid;border-bottom-style: solid; border-color: #555;">{{ comment.comment }}</p>
            {% endfor %}
        </div>
    </div>






{% endblock %}

meduzer/blog/templates/blog/post/post_form.html
{% extends 'base.html' %}


{% block title %}
    Создать публикацию - {{block.super}}
{% endblock %}

    {% block mark_style %}
    {{ form.media }}
    {% endblock mark_style %}

{% block content %}

    <form  class="" action="{% url 'blog:post_create_url' %}" method="post">
        {% csrf_token %}
        <style class="text/css">
            .wmd-button-row {
            background: white;
            margin:-top: 1rem;
            margin-bottom: 1rem;
            margin-left:0;
            margin-right:0;
            }
            .wmd-panel {
            width: initial;
            margin: 0;
            }
            .wmd-input {
            background: white;
            }
            .form-group {
            margin-top:20px;
            }
            .form-control {
            margin-top:10px;
            margin-bottom:20px;
            }
        </style>

        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" name="button" class="btn btn-primary btn-sm" style="margin-bottom: 20px;"> Опубликовать</button>
        <a href="{% url 'blog:tag_create_url' %}" type="submit" name="button" class="btn btn-warning btn-sm float-right" style="margin-bottom: 20px;"> Создать метку</a>
    </form>
{% endblock %}

meduzer/blog/templates/blog/post/post_list.html
{% extends 'base.html' %}



{% block title %}
    Список публикаций
{% endblock %}

{% block content %}
    {% for post in object_list %}
        {% include 'blog/includes/post_card_template.html' %}
    {% endfor %}
{% endblock %}

meduzer/blog/templates/blog/post/post_update_form.html
{% extends 'base.html' %}

{% block title %}
    Редактировать публикацию: "{{ post.title }}"- {{ block.super }}
{% endblock %}


{% block content %}

    <form class="" action="{{ post.get_update_url }}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" name="button" class="btn btn-primary">Сохранить изменения</button>
    </form>


{% endblock %}

meduzer/blog/templates/blog/post/post_upgrade_form.html
{% extends 'base.html' %}

{% block title %}
    Редактировать публикацию: "{{ post.title }}"- {{ block.super }}
{% endblock %}


{% block content %}

    <form class="" action="{{ post.get_update_url }}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" name="button" class="btn btn-primary">Сохранить изменения</button>
    </form>


{% endblock %}

meduzer/blog/templates/blog/post/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
  {% if query %}
    <h1>Публикации содержащие "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Найдено: {{ total_results }} {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in object_list %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>По Вашему запросу ничего не найдено.</p>
    {% endfor %}
    <p><a href="{% url 'blog:search_results' %}">Искать далее</a></p>
  {% else %}
    <h1>Поиск публикаций</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Поиск">
    </form>
  {% endif %}
{% endblock %}

meduzer/blog/templates/blog/post/share.html
{% extends "base.html" %}

{% block title %}Поделиться статьёй{% endblock %}

{% block content %}
  {% if sent %}
    <h3>Вы поделились статьёй</h3>
    <p>
      "{{ post.title }}" Успешно отправлено! {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h3>Поделиться "{{ post.title }}"</h3>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Поделиться">
    </form>
  {% endif %}
{% endblock %}